### ISSUE TITLE
RFC: RFC process

### ISSUE THREAD

**Issue by adamcrume** [google/tensorflow-rust#13]
# Overview
We need a way to discuss design decisions, meta-issues, and other things that people are likely to have differing opinions on.  RFCs are not for feature requests or bikeshedding.  They're for situations where a difference of opinion exists on major issues.

# Process
1. Someone opens a GitHub issue with a title starting with "Proposed RFC:".  The proposal, any alternatives, and arguments for/against are laid out.
2. If it's worth discussing, I'll tag it with RFC and remove the word "Proposed".  A date for the end of the comment period is given.
3. The RFC stays open until the end of the comment period, although the date is not fixed and may be extended if there is good reason.  Commenters may propose additional suggestions, in addition to providing arguments for/against existing suggestions.
4. I'll comment on the issue with a decision and close the issue.

# Alternatives

## No RFC process
I'd like to make sure everyone's voice is heard, so there should probably be some sort of process.  Having a process also means that the rationale for decisions can be looked up in the future, and it's clear whether a decision has been made or not.

## RFCs in the wiki
That might be too unstructured.  Anyone could edit anything, rather than using a nice comment system.  I wouldn't have a way to tag things as RFCs that other people couldn't also do.

## Discussion on IRC
Simple and informal, but not everyone uses IRC.  Not everyone is online all the time, either.  It also doesn't keep discussions about separate RFCs separate.  It's also not possible to do things like search for open RFCs.

## A more formal process, like the one for the Rust language
We probably don't need that much overhead.

# Questions

- What should the default comment period be?  It depends on the issue, of course, but a good default might be two weeks.
- Should we bother with RFC numbering?  How should they be numbered?  We could simply use the issue number, if we use the issue tracker for RFCs.  The numbers won't be contiguous, but maybe that doesn't matter.

# Meta
This will be closed on July 30, 2016 unless extended.

**Comment by posix4e** [comment]
Sounds good. Let's give the main suggestion a try.

**Comment by adamcrume** [comment]
Hm, not much participation.  (Except for posix4e.  Thanks for commenting!)  I'm not sure if it's because the audience is small, or because the RFCs weren't advertised well enough.  I'm going to extend both RFCs until August 31 and advertise them in the README.

**Comment by IvanUkhov** [comment]
It might help if people could discover the crate starting from the official website of TensorFlow. One could, for instance, mention Rust on the [API Documentation](https://www.tensorflow.org/versions/master/api_docs/index.html) page and add a link to the crate in the [Community](https://www.tensorflow.org/versions/master/resources/index.html#community) section or on a page linked from that section such as [Awesome TensorFlow](https://github.com/jtoy/awesome-tensorflow).

**Comment by adamcrume** [comment]
Good idea.  I submitted a pull request to add a link to the Community section: https://github.com/tensorflow/tensorflow/pull/3702

**Comment by adamcrume** [comment]
No real resolution.  I'll just skip RFCs for now, unless/until there's more community interest.
