### ISSUE TITLE
Cast between unsigned and signed integers in Tensor

### ISSUE THREAD

**Issue by IvanUkhov** [google/tensorflow-rust#17]
`Tensor:: new_with_buffer` [casts](https://github.com/google/tensorflow-rust/blob/916e83a5dd6b549edffedae703505c2c2d8be8da/src/lib.rs#L641) `*const usize` to `*const int64_t` when feeding dimensions to `TF_NewTensor`. I just wanted to confirm that it’s done intentionally (for performance reasons or otherwise) as it could lead to surprising results in some cases. Thank you.

A side note: in Python, one can write `-1` for one of the dimensions so that TensorFlow figures out by itself what that dimension should be. I wonder whether it works the same way through the C API and, if it does, whether the crate would like to preserve this behavior.

Regards,
Ivan

**Comment by adamcrume** [comment]
Waiting to hear back what the TensorFlow C API is supposed to look like: https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/IAJ0NQyCHPQ

**Comment by adamcrume** [comment]
Finally heard back.  They want to use int64_t everywhere: https://groups.google.com/a/tensorflow.org/d/msg/discuss/IAJ0NQyCHPQ/xlGhgmLPAwAJ.  They never explicitly said anything about signedness, but since they want int64_t, I say we use i64 for consistency.
