### ISSUE TITLE
No C API in TensorFlow v0.10

### ISSUE THREAD

**Issue by IvanUkhov** [google/tensorflow-rust#18]
I might be misunderstanding what’s happening, but it [seems](https://github.com/tensorflow/tensorflow/issues/4277) that one won’t be able to upgrade TensorFlow to version 0.10 as the C API somehow has become unusable and, hence, will not be easily accessible in the upcoming release. I’ve tried to [play a bit](https://github.com/stainless-steel/tensorflux-sys/blob/master/examples/multiplication.rs#L39) with the new API functions when they were still being compiled and included in `libtensorflow.so`, and it seemed to be working nicely. Perhaps they think that this functionality is still raw, and that’s why they don’t want to expose it just yet. The bottom line is that the crate won’t have the graph-construction functionality in the nearest future. I’m wondering if you have more information on this. Thanks!

Regards,
Ivan

**Comment by adamcrume** [comment]
That's unfortunate.  I'm working on an update using the new API in v0.10.0rc0, which works fine. I'm surprised they'd make that change between a release candidate and the actual release.  If that small [BUILD file change](https://github.com/tensorflow/tensorflow/commit/d03f2545ecc3012e6c941a3a1e957f7d7f8d5040) is all that's needed to get 0.10.0 to work, we might just patch it in when building from source.

**Comment by rschulman** [comment]
Is this issue why I'm also unable to find the `tensorflow/core/public/tensor_c_api.h` file that the readme refers to?

**Comment by adamcrume** [comment]
It's related.  Thanks for pointing that out; I need to update the README.  If you don't need to use TensorFlow outside of Rust, you can actually skip nearly everything in the "Building" section of the README.  (Except for installing Bazel.  You do need to do that.)

Anyway, in a recent change to TensorFlow, they moved the file to $TENSORFLOW_SRC/tensorflow/c/c_api.h.  The shared library moved, too.  You need to run `bazel build -c opt tensorflow:tensorflow_c.so` and copy $TENSORFLOW_SRC/bazel-bin/tensorflow/tensorflow_c.so to /usr/local/lib/tensorflow.so (note the file rename).

**Comment by rschulman** [comment]
Bazel gives me `ERROR: no such target '//tensorflow:tensorflow_c.so': target 'tensorflow_c.so' not declared in package 'tensorflow'` and suggests I might mean `libtensorflow_c.so` instead. Is that right?

**Comment by adamcrume** [comment]
Yes it is, sorry.

**Comment by adamcrume** [comment]
We manually patch in the build rule after cloning TensorFlow, so we can use v0.10.0 now.
