### ISSUE TITLE
libc::memalign not supported on OSX

### ISSUE THREAD

**Issue by ujh** [google/tensorflow-rust#4]
On OSX libc doesn't support `memalign`. It does however support `posix_memalign` but changing the code to use that instead results in a segfault. I probably just don't know how to use it.

**Comment by adamcrume** [comment]
Let me know if that segfaults.  I don't have an OSX instance handy to test with.

**Comment by ujh** [comment]
Thank you so much, that seems to work. I can run the tests and there's no segfault. 👍
