### ISSUE TITLE
mac lacks `memalign`

### ISSUE THREAD

**Issue by ptrsxu** [google/tensorflow-rust#5]
It seems that mac os x lacks the function `memalign` called in src/buffer.rs. and the compilation would result as ``error: unresolved name `libc::memalign` [E0425]``.

**Comment by ujh** [comment]
Have you tried the latest master code? I reported the same issue as #4 not too long ago and I can now build the project on OSX.

**Comment by adamcrume** [comment]
I also pushed version 0.0.2 with the fix, in case you're using crates.io.

**Comment by ptrsxu** [comment]
Yes, It works for version 0.0.2 using crates.io now. thanks a lot...
