### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by posix4e** [google/tensorflow-rust#7]
Sorry for being late to the party. I'd love to add some working examples and create a examples/ directory. Sound good? Got any pointers before I get started?

**Comment by adamcrume** [comment]
Examples sound great!  A very basic example could be written based on `test_run` in `src/lib.rs`.  Until #3 is fixed, a complete example would probably include a Python program to generate a graph.

**Comment by adamcrume** [comment]
We have a couple of examples that use a graph generated in Python, and one using pure Rust.  Closing since we have some examples now, but of course more examples (especially more diverse examples) are always welcome.
