### ISSUE TITLE
Call to communicate/ Call to action

### ISSUE THREAD

**Issue by posix4e** [google/tensorflow-rust#8]
It's really nice when on the front page it's super obvious how to get involved. I'm happy to make doc changes, and I assume I don't need to sign a CA for README changes. What is this project's preferred MO for communication? Do we have an irc channel? Can I start one on mozilla?

**Comment by adamcrume** [comment]
We don't have any communication channels at the moment, outside of the issue tracker. IRC wouldn't be my personal first choice, but I know it's popular with Rust developers, so that's fine.  As far as I know, you do have to sign a CLA for any submissions at all.

**Comment by posix4e** [comment]
Signed. I even asked my boss. What do you think about a rust-tensorflow irc
room on mozilla. I filed a pull request with a badge for it.

On Mon, Jul 11, 2016 at 8:25 PM Adam Crume <notifications@github.com> wrote:

> We don't have any communication channels at the moment, outside of the
> issue tracker. IRC wouldn't be my personal first choice, but I know it's
> popular with Rust developers, so that's fine. As far as I know, you do have
> to sign a CLA for any submissions at all.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/tensorflow-rust/issues/8#issuecomment-231927907>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAxN20-VdQLc2Ar8mMbn2iyWM4r3L9cnks5qUwk-gaJpZM4JJBAY>
> .
>
-- 
Sent from my mobile 4045076749
Alex Newman

**Comment by adamcrume** [comment]
I'd rather go with #tensorflow-rust, since that matches the project name.

**Comment by IvanUkhov** [comment]
It might be interesting to have a look at how other projects in the Rust community do it. For instance, [Rusty Machine](https://github.com/AtheMathmo/rusty-machine), a machine-learning library, uses a Gitter channel. As far as I can tell, Google is OK with that as they use Gitter for some of their projects too such as [Material Design Lite](https://github.com/google/material-design-lite).

**Comment by posix4e** [comment]
I would suggest a new ticket if we want to discuss gitter. I personally am
turned off by projects which move to slack or gitter, but in the web world
it's pretty normal.

On Wed, Jul 13, 2016 at 11:18 PM Ivan Ukhov <notifications@github.com>
wrote:

> It might be interesting to have a look at how other projects in the Rust
> community do it. For instance, Rusty Machine
> <https://github.com/AtheMathmo/rusty-machine>, a machine-learning
> library, uses a Gitter channel. As far as I can tell, Google is OK with
> that as they use Gitter for some of their projects too such as Material
> Design Lite <https://github.com/google/material-design-lite>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/tensorflow-rust/issues/8#issuecomment-232566565>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAxN2_9SLopxbS_V1wFFzC1bUBs7dIgCks5qVdSngaJpZM4JJBAY>
> .
>
-- 
Sent from my mobile 4045076749
Alex Newman
